### PR TITLE
Adding ability to configure base url from config and use a different json library

### PR DESCRIPTION
**Pull request by leiyangyou**

### CODE REVIEW

**Comment by teamon** [comment]
@leiyangyou Thanks a lot! I'll do my best to review this in next couple of days.

**Comment by Wijnand** [comment]
Any news on this pull request? The last commit fixes Testla for Elixir 1.2

**Comment by teamon** [comment]
@Wijnand Fix for 1.2 has been added to master (https://github.com/monterail/tesla/releases/tag/v0.2.0) 

@leiyangyou Thanks a lot for all the changes. I will cherry pick the commits and put all of that together.

**Comment by teamon** [comment]
All merged and v0.2.1 released.

**Pull request closed without merging**
